In [63]:
import scipy.io
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
from sklearn.utils import shuffle
import matplotlib.pyplot as plt
%matplotlib inline

In [64]:
mat = scipy.io.loadmat('C:/Users/eacun/Downloads/dataset55_release2.mat')
mat.items()

dict_items([('__header__', b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Wed Jul 22 14:13:11 2020'), ('__version__', '1.0'), ('__globals__', []), ('addedNoisePercent', array([[0.1],
       [0.5],
       [0. ],
       ...,
       [1. ],
       [0.1],
       [0. ]])), ('labels', array([[ 1],
       [ 1],
       [ 1],
       ...,
       [55],
       [55],
       [55]], dtype=uint8)), ('massLoadings', array([[90.48134734],
       [90.48134734],
       [90.48134734],
       ...,
       [93.56603952],
       [93.56603952],
       [93.56603952]])), ('spectra', array([[0.01684698, 0.01575019, 0.01553012, ..., 0.01631328, 0.01523777,
        0.01464116],
       [0.01862416, 0.01217942, 0.02092375, ..., 0.01522821, 0.02158774,
        0.01224737],
       [0.01634829, 0.01627708, 0.01620733, ..., 0.01681628, 0.01679286,
        0.0167685 ],
       ...,
       [0.01777366, 0.02470746, 0.04042846, ..., 0.52899222, 0.53342443,
        0.54125978],
       [0.03112273, 0.02996503, 0.03299245, ..., 0.54179967, 0.53942979,
        0.54275879],
       [0.03236588, 0.0324536 , 0.03238276, ..., 0.54378712, 0.54383177,
        0.54386556]])), ('substrateIDs', array([[1],
       [1],
       [1],
       ...,
       [8],
       [8],
       [8]], dtype=uint8)), ('substrateSpectra', array([[0.008192, 0.008116, 0.008042, ..., 0.010792, 0.010765, 0.010737],
       [0.035105, 0.035617, 0.036458, ..., 0.041036, 0.041051, 0.04107 ],
       [0.585617, 0.585672, 0.585179, ..., 0.559301, 0.559264, 0.55923 ],
       ...,
       [0.035515, 0.035251, 0.034737, ..., 0.247776, 0.246856, 0.245963],
       [0.031312, 0.031438, 0.031556, ..., 0.569884, 0.56993 , 0.569966],
       [0.00088 , 0.001132, 0.004165, ..., 0.008746, 0.008464, 0.008364]]))])

In [65]:
y=mat['labels']
df=mat['spectra']
df=pd.DataFrame(df)
print(df.shape)

(49500, 1701)

In [66]:
ys=mat['substrateIDs']
subs=mat['substrateSpectra']
subs=pd.DataFrame(subs)

In [67]:
df['Analyte']=y
df['substrate']=ys

In [68]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,1693,1694,1695,1696,1697,1698,1699,1700,Analyte,substrate
0,0.016847,0.015750,0.015530,0.014852,0.015202,0.015420,0.016572,0.014220,0.014954,0.014995,...,0.016104,0.017741,0.017533,0.016542,0.016122,0.016313,0.015238,0.014641,1,1
1,0.018624,0.012179,0.020924,0.003329,0.014498,0.019329,0.011184,0.010919,0.007558,0.017733,...,0.010701,0.018193,0.017089,0.018461,0.020192,0.015228,0.021588,0.012247,1,1
2,0.016348,0.016277,0.016207,0.016139,0.016066,0.015951,0.015780,0.015613,0.015557,0.015594,...,0.016926,0.016905,0.016884,0.016862,0.016839,0.016816,0.016793,0.016769,1,1
3,0.015725,0.018253,0.018749,0.017823,0.016850,0.015230,0.017195,0.011854,0.013581,0.011075,...,0.020200,0.018257,0.012629,0.014090,0.016704,0.016195,0.017715,0.011852,1,1
4,0.018868,0.024683,0.016563,0.020112,0.018959,0.017602,0.016099,0.009405,0.020006,0.019105,...,0.011581,0.019433,0.015924,0.006780,0.015658,0.017236,0.019725,0.015868,1,1

In [69]:
df = shuffle(df)
df

,0,1,2,3,4,5,6,7,8,9,...,1693,1694,1695,1696,1697,1698,1699,1700,Analyte,substrate
37489,0.076980,0.103928,0.137631,0.157774,0.171761,0.183628,0.191896,0.195766,0.198635,0.201146,...,0.638444,0.638791,0.639159,0.639495,0.639805,0.640063,0.640222,0.640325,45,4
29138,0.036098,0.035650,0.035203,0.034611,0.034174,0.033814,0.033428,0.032972,0.032596,0.032232,...,0.240452,0.239692,0.238892,0.238119,0.237323,0.236450,0.235568,0.234732,17,7
35297,0.048323,0.050566,0.049114,0.048659,0.048519,0.048269,0.050817,0.050303,0.049208,0.049922,...,0.561068,0.559515,0.560125,0.561081,0.559909,0.561819,0.561387,0.562597,23,4
33005,0.119245,0.133809,0.120324,0.127955,0.124842,0.110518,0.113985,0.118021,0.124434,0.127495,...,0.589790,0.592626,0.560811,0.577699,0.586784,0.587117,0.594930,0.582961,1,4
12058,0.037796,0.031582,0.038614,0.037331,0.041247,0.041559,0.038865,0.036977,0.034931,0.041477,...,0.041787,0.041820,0.043076,0.046077,0.043538,0.045516,0.045844,0.044723,11,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17942,0.020277,0.017991,0.019100,0.020838,0.020137,0.019342,0.020057,0.021168,0.020326,0.021424,...,0.028288,0.028416,0.030714,0.029007,0.029749,0.027808,0.028114,0.029249,15,5
46533,0.033577,0.032667,0.033259,0.032197,0.032925,0.033733,0.031682,0.032405,0.030941,0.031794,...,0.556126,0.556203,0.556137,0.557299,0.556528,0.556125,0.556349,0.556614,26,8
1618,0.014126,0.006940,0.009278,0.009070,0.007170,0.009290,0.009835,0.013522,0.006983,0.011022,...,0.012349,0.012158,0.009835,0.012253,0.012725,0.012769,0.012073,0.014633,17,1
25323,0.064189,0.063797,0.059437,0.067104,0.060202,0.059993,0.057435,0.059516,0.053403,0.056513,...,0.261828,0.264284,0.262534,0.265549,0.262854,0.258874,0.259641,0.262270,34,6
12343,0.030946,0.019971,0.045420,0.042749,0.046761,0.051186,0.044796,0.041340,0.032326,0.034903,...,0.039672,0.044702,0.054999,0.031079,0.052186,0.056717,0.046951,0.046037,14,2

In [70]:
df.reset_index(inplace=True, drop=True) 
df.head()

,0,1,2,3,4,5,6,7,8,9,...,1693,1694,1695,1696,1697,1698,1699,1700,Analyte,substrate
0,0.076980,0.103928,0.137631,0.157774,0.171761,0.183628,0.191896,0.195766,0.198635,0.201146,...,0.638444,0.638791,0.639159,0.639495,0.639805,0.640063,0.640222,0.640325,45,4
1,0.036098,0.035650,0.035203,0.034611,0.034174,0.033814,0.033428,0.032972,0.032596,0.032232,...,0.240452,0.239692,0.238892,0.238119,0.237323,0.236450,0.235568,0.234732,17,7
2,0.048323,0.050566,0.049114,0.048659,0.048519,0.048269,0.050817,0.050303,0.049208,0.049922,...,0.561068,0.559515,0.560125,0.561081,0.559909,0.561819,0.561387,0.562597,23,4
3,0.119245,0.133809,0.120324,0.127955,0.124842,0.110518,0.113985,0.118021,0.124434,0.127495,...,0.589790,0.592626,0.560811,0.577699,0.586784,0.587117,0.594930,0.582961,1,4
4,0.037796,0.031582,0.038614,0.037331,0.041247,0.041559,0.038865,0.036977,0.034931,0.041477,...,0.041787,0.041820,0.043076,0.046077,0.043538,0.045516,0.045844,0.044723,11,2

In [71]:
dfsub1=df[df['substrate']==1]
dfsub2=df[df['substrate']==2]
dfsub3=df[df['substrate']==3]
dfsub4=df[df['substrate']==4]
dfsub5=df[df['substrate']==5]
dfsub6=df[df['substrate']==6]
dfsub7=df[df['substrate']==7]
dfsub8=df[df['substrate']==8]
dfsub9=df[df['substrate']==9]

In [72]:
mdfsub1=dfsub1.iloc[:,0:1701]
mdfsub2=dfsub2.iloc[:,0:1701]
mdfsub3=dfsub3.iloc[:,0:1701]
mdfsub4=dfsub4.iloc[:,0:1701]
mdfsub5=dfsub5.iloc[:,0:1701]
mdfsub6=dfsub6.iloc[:,0:1701]
mdfsub7=dfsub7.iloc[:,0:1701]
mdfsub8=dfsub8.iloc[:,0:1701]
mdfsub9=dfsub9.iloc[:,0:1701]

In [73]:
dfsub1.head()

,0,1,2,3,4,5,6,7,8,9,...,1693,1694,1695,1696,1697,1698,1699,1700,Analyte,substrate
10,0.011133,0.013846,0.017921,0.020074,0.010530,0.020593,0.009141,0.010260,0.016677,0.016437,...,0.015212,0.019210,0.015201,0.018826,0.021463,0.011524,0.019620,0.024540,35,1
13,0.017713,0.016427,0.015536,0.017573,0.017062,0.015253,0.016672,0.018377,0.017275,0.015804,...,0.019726,0.017683,0.018187,0.020514,0.017941,0.018822,0.017321,0.018090,26,1
15,0.012966,0.012978,0.012485,0.012960,0.012065,0.011119,0.012719,0.011996,0.013895,0.012859,...,0.014395,0.014794,0.015097,0.015185,0.015196,0.013821,0.014553,0.014921,24,1
19,0.011222,0.014224,0.025649,0.006964,0.015276,0.016317,0.016977,0.029150,0.019311,0.013204,...,0.023793,0.000698,0.014576,0.033253,0.001828,0.007183,0.002264,0.003343,21,1
24,0.010915,0.014540,0.006713,0.009176,0.008657,0.010163,0.008613,0.009074,0.010196,0.012984,...,0.009423,0.015023,0.009800,0.008574,0.008712,0.016131,0.015911,0.011238,27,1

In [74]:
s1=subs.loc[0,:]
s2=subs.loc[1,:]
s3=subs.loc[2,:]
s4=subs.loc[3,:]
s5=subs.loc[4,:]
s6=subs.loc[5,:]
s7=subs.loc[6,:]
s8=subs.loc[7,:]
s9=subs.loc[8,:]

In [75]:
modsub1=mdfsub1.apply(lambda x : x -(np.sum(np.array(x)*np.array(s1))/np.sum(np.array(s1)*np.array(s1)))*s1,axis=1)
modsub2=mdfsub2.apply(lambda x : x -(np.sum(np.array(x)*np.array(s2))/np.sum(np.array(s2)*np.array(s2)))*s2,axis=1)
modsub3=mdfsub3.apply(lambda x : x -(np.sum(np.array(x)*np.array(s3))/np.sum(np.array(s3)*np.array(s3)))*s3,axis=1)
modsub4=mdfsub4.apply(lambda x : x -(np.sum(np.array(x)*np.array(s4))/np.sum(np.array(s4)*np.array(s4)))*s4,axis=1)
modsub5=mdfsub5.apply(lambda x : x -(np.sum(np.array(x)*np.array(s5))/np.sum(np.array(s5)*np.array(s5)))*s5,axis=1)
modsub6=mdfsub6.apply(lambda x : x -(np.sum(np.array(x)*np.array(s6))/np.sum(np.array(s6)*np.array(s6)))*s6,axis=1)
modsub7=mdfsub7.apply(lambda x : x -(np.sum(np.array(x)*np.array(s7))/np.sum(np.array(s7)*np.array(s7)))*s7,axis=1)
modsub8=mdfsub8.apply(lambda x : x -(np.sum(np.array(x)*np.array(s8))/np.sum(np.array(s8)*np.array(s8)))*s8,axis=1)
modsub9=mdfsub9.apply(lambda x : x -(np.sum(np.array(x)*np.array(s9))/np.sum(np.array(s9)*np.array(s9)))*s9,axis=1)

In [76]:
subdf=[modsub1,modsub2,modsub3,modsub4,modsub5,modsub6,modsub7,modsub8,modsub9]
cent_subs=pd.concat(subdf)
cent_subs.head()

,0,1,2,3,4,5,6,7,8,9,...,1691,1692,1693,1694,1695,1696,1697,1698,1699,1700
10,-0.003056,-0.000211,0.003992,0.006270,-0.003152,0.007032,-0.004305,-0.003072,0.003457,0.003325,...,0.000904,0.001223,-0.003700,0.000340,-0.003626,0.000042,0.002726,-0.007168,0.000975,0.005943
13,0.002013,0.000873,0.000124,0.002299,0.001924,0.000247,0.001794,0.003626,0.002647,0.001297,...,-0.000946,-0.003147,-0.001199,-0.003196,-0.002644,-0.000270,-0.002791,-0.001860,-0.003309,-0.002487
15,0.001719,0.001834,0.001443,0.002017,0.001220,0.000368,0.002060,0.001428,0.003414,0.002465,...,-0.000402,-0.000261,-0.000597,-0.000166,0.000172,0.000294,0.000343,-0.000996,-0.000228,0.000178
19,-0.001407,0.001712,0.013251,-0.005323,0.003098,0.004245,0.005009,0.017284,0.007543,0.001534,...,-0.006798,0.002506,0.006960,-0.016099,-0.002181,0.016534,-0.014850,-0.009455,-0.014332,-0.013210
24,0.001582,0.005293,-0.002449,0.000095,-0.000342,0.001242,-0.000232,0.000304,0.001500,0.004359,...,0.000796,-0.002286,-0.003017,0.002610,-0.002585,-0.003782,-0.003613,0.003835,0.003646,-0.000996

In [77]:
cent_subs.shape

(49500, 1701)

In [78]:
# Using sklearn
from sklearn.preprocessing import normalize
b=cent_subs.iloc[:,0:1701]
b.head()

,0,1,2,3,4,5,6,7,8,9,...,1691,1692,1693,1694,1695,1696,1697,1698,1699,1700
10,-0.003056,-0.000211,0.003992,0.006270,-0.003152,0.007032,-0.004305,-0.003072,0.003457,0.003325,...,0.000904,0.001223,-0.003700,0.000340,-0.003626,0.000042,0.002726,-0.007168,0.000975,0.005943
13,0.002013,0.000873,0.000124,0.002299,0.001924,0.000247,0.001794,0.003626,0.002647,0.001297,...,-0.000946,-0.003147,-0.001199,-0.003196,-0.002644,-0.000270,-0.002791,-0.001860,-0.003309,-0.002487
15,0.001719,0.001834,0.001443,0.002017,0.001220,0.000368,0.002060,0.001428,0.003414,0.002465,...,-0.000402,-0.000261,-0.000597,-0.000166,0.000172,0.000294,0.000343,-0.000996,-0.000228,0.000178
19,-0.001407,0.001712,0.013251,-0.005323,0.003098,0.004245,0.005009,0.017284,0.007543,0.001534,...,-0.006798,0.002506,0.006960,-0.016099,-0.002181,0.016534,-0.014850,-0.009455,-0.014332,-0.013210
24,0.001582,0.005293,-0.002449,0.000095,-0.000342,0.001242,-0.000232,0.000304,0.001500,0.004359,...,0.000796,-0.002286,-0.003017,0.002610,-0.002585,-0.003782,-0.003613,0.003835,0.003646,-0.000996

In [79]:
#normalize(b)
b1=b.apply(lambda x: x/(x**2).sum()**.5, axis=1)
b1.head()

,0,1,2,3,4,5,6,7,8,9,...,1691,1692,1693,1694,1695,1696,1697,1698,1699,1700
10,-0.011102,-0.000766,0.014501,0.022777,-0.011450,0.025545,-0.015638,-0.011159,0.012557,0.012080,...,0.003283,0.004442,-0.013441,0.001234,-0.013173,0.000154,0.009903,-0.026042,0.003542,0.021591
13,0.009975,0.004325,0.000616,0.011391,0.009534,0.001225,0.008891,0.017967,0.013114,0.006427,...,-0.004688,-0.015592,-0.005943,-0.015836,-0.013103,-0.001337,-0.013830,-0.009217,-0.016397,-0.012320
15,0.015181,0.016200,0.012745,0.017813,0.010773,0.003248,0.018200,0.012614,0.030159,0.021775,...,-0.003547,-0.002309,-0.005274,-0.001462,0.001523,0.002600,0.003028,-0.008801,-0.002012,0.001577
19,-0.003318,0.004035,0.031237,-0.012549,0.007303,0.010008,0.011808,0.040744,0.017782,0.003616,...,-0.016026,0.005907,0.016407,-0.037951,-0.005143,0.038976,-0.035007,-0.022288,-0.033786,-0.031142
24,0.014168,0.047412,-0.021942,0.000855,-0.003067,0.011123,-0.002081,0.002725,0.013434,0.039053,...,0.007130,-0.020479,-0.027028,0.023381,-0.023157,-0.033881,-0.032367,0.034355,0.032665,-0.008919

In [80]:
a1=np.array(dfsub1['Analyte'].values.tolist())
a2=np.array(dfsub2['Analyte'].values.tolist())
a3=np.array(dfsub3['Analyte'].values.tolist())
a4=np.array(dfsub4['Analyte'].values.tolist())
a5=np.array(dfsub5['Analyte'].values.tolist())
a6=np.array(dfsub6['Analyte'].values.tolist())
a7=np.array(dfsub7['Analyte'].values.tolist())
a8=np.array(dfsub8['Analyte'].values.tolist())
a9=np.array(dfsub9['Analyte'].values.tolist())
y=np.concatenate((a1,a2,a3,a4,a5,a6,a7,a8,a9),axis=None)
print(y)

[35 26 24 ... 16 36 34]

In [81]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
# We will find by inspection the best k according to the classifier accuracy on the test set
accuracies = []
X=b1.iloc[:,0:1701]
# We will find by inspection the best k according to the classifier accuracy on the test set
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2,random_state=0)
for k in range(1, 40, 2):
    # Entrenar el clasificador  con el valor actual de  `k`
    neigh = KNeighborsClassifier(n_neighbors=k)
    neigh.fit(X_train, y_train)

    # Evaluar los modelos e imprimiendo sus predicciones
    score = neigh.score(X_test, y_test)
    print("k=%d, accuracy=%.2f%%" % (k, score * 100))
    accuracies.append(score)

k=1, accuracy=85.35%
k=3, accuracy=86.10%
k=5, accuracy=86.37%
k=7, accuracy=86.57%
k=9, accuracy=86.70%
k=11, accuracy=86.77%
k=13, accuracy=86.82%
k=15, accuracy=86.80%
k=17, accuracy=86.64%
k=19, accuracy=86.49%
k=21, accuracy=85.96%
k=23, accuracy=85.46%
k=25, accuracy=84.98%
k=27, accuracy=84.02%
k=29, accuracy=83.09%
k=31, accuracy=82.33%
k=33, accuracy=81.37%
k=35, accuracy=80.46%
k=37, accuracy=79.56%
k=39, accuracy=79.14%

In [82]:
#metrics for k=13
import time
from sklearn.metrics import classification_report, confusion_matrix, f1_score, precision_score, roc_auc_score
neigh = KNeighborsClassifier(n_neighbors=13)
X=b1.iloc[:,0:1701]
neigh.fit(X, y) 
print("Accuracy estimated by resubstitution", neigh.score(X,y))
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2,random_state=0)
start_time = time.time()
neigh = KNeighborsClassifier(n_neighbors=13)
neigh.fit(X_train, y_train) 
#Calculating  metrics of prediction
predictions = neigh.predict(X_test)
print("F1-score is=",f1_score(y_test,predictions, average="weighted"))
print("The accuracy is=",neigh.score(X_test,y_test))
print("--- %s seconds ---" % (time.time() - start_time))

Accuracy estimated by resubstitution 0.8798585858585859
F1-score is= 0.8678623277380016
The accuracy is= 0.8681818181818182
--- 37.39564919471741 seconds ---

In [83]:
#Calculating metrics for each class
print("EVALUATION ON TESTING DATA")
print(classification_report(y_test, predictions))

EVALUATION ON TESTING DATA
              precision    recall  f1-score   support

           1       0.78      0.93      0.84       175
           2       0.80      0.84      0.82       189
           3       0.84      0.88      0.86       181
           4       0.81      0.84      0.82       183
           5       0.81      0.89      0.85       179
           6       0.80      0.94      0.87       164
           7       0.85      0.93      0.89       176
           8       0.88      0.86      0.87       169
           9       0.88      0.94      0.91       185
          10       0.85      0.87      0.86       203
          11       0.87      0.92      0.89       186
          12       0.89      0.90      0.89       182
          13       0.83      0.89      0.86       160
          14       0.87      0.84      0.85       195
          15       0.82      0.85      0.84       183
          16       0.86      0.88      0.87       164
          17       0.88      0.88      0.88       197
          18       0.90      0.86      0.88       193
          19       0.86      0.88      0.87       177
          20       0.87      0.86      0.87       183
          21       0.88      0.91      0.90       183
          22       0.83      0.86      0.85       178
          23       0.87      0.90      0.88       181
          24       0.88      0.88      0.88       145
          25       0.87      0.85      0.86       205
          26       0.86      0.84      0.85       190
          27       0.85      0.73      0.79       190
          28       0.85      0.85      0.85       185
          29       0.85      0.86      0.85       156
          30       0.84      0.74      0.79       168
          31       0.87      0.87      0.87       191
          32       0.90      0.88      0.89       195
          33       0.85      0.82      0.84       167
          34       0.87      0.89      0.88       170
          35       0.88      0.90      0.89       175
          36       0.91      0.92      0.91       190
          37       0.87      0.89      0.88       193
          38       0.93      0.86      0.89       167
          39       0.90      0.84      0.87       186
          40       0.86      0.81      0.84       171
          41       0.93      0.95      0.94       182
          42       0.85      0.82      0.84       187
          43       0.89      0.92      0.90       178
          44       0.87      0.86      0.87       169
          45       0.90      0.95      0.93       182
          46       0.90      0.84      0.87       182
          47       0.88      0.87      0.88       185
          48       0.88      0.84      0.86       173
          49       0.91      0.92      0.91       150
          50       0.92      0.80      0.85       186
          51       0.89      0.91      0.90       166
          52       0.93      0.90      0.91       182
          53       0.92      0.85      0.89       183
          54       0.85      0.83      0.84       192
          55       0.90      0.73      0.81       193

    accuracy                           0.87      9900
   macro avg       0.87      0.87      0.87      9900
weighted avg       0.87      0.87      0.87      9900

In [84]:
from sklearn.linear_model import LogisticRegression
import time
X=b1.iloc[:,0:1701]
#model.fit(X,y)
#model.score(X,y)
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2,random_state=0)
start_time = time.time()
model = LogisticRegression(solver="newton-cg",multi_class="multinomial",max_iter=5000)
model.fit(X_train,y_train)
#Calculating  metrics of prediction
predictions = model.predict(X_test)
#print(predictions)
#print("F1-score is=",f1_score(y_test,predictions, average="weighted"))
#print("precision=",precision_score(y_test,predictions,average="weighted"))
print("The accuracy is=",model.score(X_test,y_test))
print("--- %s seconds ---" % (time.time() - start_time))

The accuracy is= 0.8294949494949495
--- 141.4854199886322 seconds ---